remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Omnom Privacy Policy
description: Privacy Policy for the Omnom Recipe App
show_downloads: false

# Theme color customization
colors:
  gradient_left: "#004e92"
  gradient_right: "#00916e"
